fun main()
{
    println("Student Enrollment No.:")
    var en = readln()
    println("Student Name:")
    var name = readln()
    println("Student Branch:")
    var br = readln()
    println("Student Class:")
    var cl = readln()
    println("Student Batch:")
    var ba = readln()
    println("Student College Name:")
    var cn = readln()
    println("Student University Name:")
    var un = readln()
    println("Student Age:")
    var age = readln()
    println("*********************************")
    println("Student Enrollment No.: $en")
    println("Student Name: $name")
    println("Student Branch: $br")
    println("Student Class: $cl")
    println("Student Batch: $ba")
    println("Student College Name: $cn")
    println("Student University Name: $un")
    println("Student Age: $age")


}